import { defineConfig, globalIgnores } from "eslint/config";
import tseslint from "typescript-eslint";

/**
 * Deliberately **not** `eslint-config-expo`.
 *
 * That is the config Expo ships and it would add React Native specific rules
 * worth having — but it is a new dependency, and rule 12 says to ask before
 * taking one. The project has added exactly one runtime dependency since
 * v1.0.0 and it was approved first. So this config is built from `eslint`
 * and `typescript-eslint`, both of which are already in the lockfile as the
 * web app's linting toolchain; nothing new enters the repository.
 *
 * Declared in apps/mobile/package.json rather than relied on through
 * hoisting. Phase 0 had three undeclared imports that only resolved because
 * npm flattened node_modules, and pnpm's isolated linker is precisely the
 * thing that stops that working — see the note in .npmrc.
 *
 * Recorded in pending.md: if the RN-specific rules turn out to be worth it,
 * eslint-config-expo is the thing to ask for.
 */
export default defineConfig([
  globalIgnores([
    // Continuous Native Generation output. Regenerated by `expo prebuild`,
    // never edited, and full of generated Java and Objective-C that has no
    // business being linted.
    "android/**",
    "ios/**",
    ".expo/**",
    "dist/**",
    "expo-env.d.ts",
  ]),

  // typescript-eslint's `recommended` already layers ESLint's own
  // recommended set underneath, so `@eslint/js` is not imported separately —
  // it is not a declared dependency here and reaching for it through
  // hoisting is the mistake .npmrc warns about.
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        // React Native's runtime globals. Not Node's and not the browser's:
        // there is no `document` and no `window`, and a config that declared
        // them would let a genuine mistake through silently.
        console: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        __DEV__: "readonly",
        AbortSignal: "readonly",
        AbortController: "readonly",
        TextEncoder: "readonly",
        URL: "readonly",
        process: "readonly",
      },
    },
    rules: {
      // A leading underscore is the convention for "deliberately unused" —
      // a caught error nobody inspects, a positional argument that has to
      // exist for the one after it.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Rule 1: no `any` on an exported surface. The linter cannot tell
      // exported from local, so this is an error everywhere and the few
      // legitimate uses carry an explicit disable with a reason.
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
]);
